development:
  adapter: postgresql
  encoding: utf8
  database: after_commit_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: after_commit_test
  pool: 5
  username: postgres
  host: /var/run/postgresql
  password:
